### ISSUE TITLE
Negative TE values.

### ISSUE THREAD

**Issue by binbin-liu-git** [trentool/TRENTOOL3#37] opened 2022-12-17 15:50 UTC
Hi TRENTOOL community,

I am trying to use TRENTOOL3-3.4.2 to compute the Transfer Entropy between EMG and EEG signal of an  upper limb movement experiment.  There are 50 trials for each dataset, and the length of each trail is 1000ms (sampling rate 1000Hz). 

The toolbox worked quite well, however I found all the TE values in TEmat are  negative. I am really confused and don't know how to understand  and interpret these results. I am therefore writing to you in anticipation of some possible assistance. Thanks for your attention!

Binbin Liu.

**Comment by pwollstadt** [comment] 2023-01-17 15:47
Duplicate of #28 and #15

**Closed as completed by pwollstadt** 2023-01-17 15:47 UTC
