### ISSUE TITLE
TE for non stationary short time series 

### ISSUE THREAD

**Issue by ogamimusashi** [trentool/TRENTOOL3#29] opened 2018-11-04 12:48 UTC
Hello, 
I would like to test TE in the context of climate data time series. The problem is that my data is unique (numtrials = 1) and with a very low number of points (41). The times series are non stationary. 
I tried using TE_ensemble by creating ARIMA simulations of my data but it fails to capture the statistics of the original data. 
Can TE_ensemble be used with my original data or it there to few points to carry a robust TE estimation? 
How would you change the settings if so? 

Thanks

**Comment by pwollstadt** [comment] 2018-11-09 17:11
Hi @ogamimusashi, 41 samples for a non-stationary process is probably too few. The ensemble method for TE estimation expects a data set that contains many replications of a (non-stationary) process. Do you have any chance to obtain more data, ideally replications of your process?

**Comment by ogamimusashi** [comment] 2018-11-09 17:53
@pwollstadt I'm not familiar with replications in neurosciences. How replications are created? Is this simultaneous measurements or sequential?

**Comment by pwollstadt** [comment] 2018-11-09 18:21
By replications I just mean observations of temporal or physical copies of the same process. This is not specific to neuroscience measurements. In climate science, for example, this could be repeated observations of some seasonal process.

**Comment by ogamimusashi** [comment] 2018-11-09 18:51
Okay. So for example my data is annual. But i do have it at the monthly scale. To each trial could be one  year of monthly observations?

**Comment by pwollstadt** [comment] 2018-12-28 10:01
Hi @ogamimusashi sorry for the delay. Yes, if the process is stationary over years, your annual observations are one replication each. You may want to have a look at our [paper](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0102833#s2) on the ensemble method. There we describe the prerequisites for using the ensemble method (in particular, the section "Stationarity and non-stationarity in experimental time series" in the Methods).

**Comment by Cheng012** [comment] 2019-03-05 14:08
Hi @ogamimusashi @pwollstadt ,I am sorry to you.I indeed need a help. The problem is that when I try  running install.m to install the TRENTOOL toolbox, the following error shows up in MATLAB:

Error using mex
MEX cannot find library 'gpuKnnLibrary'
specified with the -l option.
MEX looks for a file with one of the
names:
libgpuKnnLibrary.lib
gpuKnnLibrary.lib
Please specify the path to this library
with the -L option.

Error in install (line 4)
mex('-v',['-L' '.'], '-lgpuKnnLibrary',
['-L' CUDA_LIB_PATH],'-lcudart',
'fnearneigh_gpu.cpp');

I can see a file named libgpuKnnLibrary.a, but no file named libgpuKnnLibrary.lib exists in the toolbox. Have you met this problem? How can i solve it?Your help will be greatly appreciated

**Comment by Xirailuyo** [comment] 2020-10-17 22:16
See my answer here @Cheng012: https://github.com/trentool/TRENTOOL3/issues/27

**Comment by pwollstadt** [comment] 2020-10-19 10:44
Hi everyone, thanks to @Xirailuyo for referencing your earlier solution to this. To add a bit of information on this: we no longer maintain TRENTOOL. So there is no update on the mex file and newer CUDA versions are no longer supported. You may want to try the workaround @Xirailuyo suggested or check out our new toolbox for information-theoretic analysis, [IDTxl](https://github.com/pwollstadt/IDTxl) written in Python. I will close this issue since this was originally on the analysis of non-stationary time series and did not see a lot of activity in the past two years. Feel free to reopen this issue if there are more questions on the original problem or move the discussion on running `install.m` to issue #27.

**Closed as completed by pwollstadt** 2020-10-19 10:44 UTC
